//
// AWSConfiguration.h
//
//
// Copyright 2015 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//

#import <AWSCore/AWSCore.h>
#import <AWSCognito/AWSCognito.h>

// AMAZON COGNITO
#define AMAZON_COGNITO_REGION AWSRegionUSEast1
#define AMAZON_COGNITO_IDENTITY_POOL_ID @"us-east-1:96664ede-71f6-4e14-a2f7-48e7cc291623"
// AMAZON MOBILE ANALYTICS
#define AMAZON_MOBILE_ANALYTICS_APP_ID @"4333f12c00934731b90943b5bbd5cf96"
// USER FILES
#define AWS_USER_FILE_MANAGER_S3_BUCKET_NAME @"socialeveningnaveens-userfiles-mobilehub-632945439"
