//
//  AWSMobileHubClient.h
//
//
// Copyright 2015 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import <AWSCore/AWSCore.h>
#import <AWSMobileAnalytics/AWSMobileAnalytics.h>

@interface AWSMobileClient : NSObject

/**
 * Amazon Mobile Analytics client - Use to generate custom or monetization analytics events.
 */
@property(atomic) AWSMobileAnalytics* mobileAnalytics;

/**
 * Retrieves a shared instance of this class.
 *
 * @return shared instance.
 */
+ (instancetype)sharedInstance;

/**
 * Configures third-party services from application delegate with options.
 *
 * @param application instance from application delegate.
 * @param launchOptions from application delegate.
 */
- (BOOL)didFinishLaunching:(UIApplication *)application withOptions:(NSDictionary *)launchOptions;

/**
 * Configure third-party services from application delegate with url, application
 * that called this provider, and any annotation info.
 *
 * @param application instance from application delegate.
 * @param url called from application delegate.
 * @param sourceApplication that triggered this call.
 * @param annotation from application delegate.
 * @return true if call was handled by this component
 */
- (BOOL)withApplication:(UIApplication *)application
                withURL:(NSURL *)url
  withSourceApplication:(NSString *)sourceApplication
         withAnnotation:(id)annotation;

/**
 * Performs any additional activation steps required of the third party services
 * e.g. Facebook
 *
 * @param application from application delegate.
 */
- (void)applicationDidBecomeActive:(UIApplication *)application;

@end
