//
//  AWSCloudLogic.h
//
//
// Copyright 2015 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//


/**
 * Cloud logic helper singleton class that provides convenient interface to invoke
 * AWS Lambda functions and handle the results asynchronously.
 */
@interface AWSCloudLogic : NSObject

/**
 * Get the singleton instance of this class.
 * @return singleton instance
 */
+ (instancetype)sharedInstance;

/**
 * Invokes the specified AWS Lambda function and passes the results and possible
 * error back to the application asynchronously.
 * @param name AWS Lambda function name, e.g., hello-world
 * @param parameters key/value pair parameters to pass to the function
 * @param completionBlock handler for results from the function
 */
- (void)invokeFunction:(NSString *)name withParameters:(NSDictionary *)parameters
   withCompletionBlock:(void (^)(NSDictionary *result, NSError *error))completionBlock;

@end
