//
//  AWSFacebookSignInProvider.h
//
//
// Copyright 2015 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//

#import "AWSFacebookSignInProvider.h"
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <FBSDKLoginKit/FBSDKLoginKit.h>
#import <AWSCore/AWSCore.h>
#import "AWSIdentityManager.h"

NSString *const AWSFacebookSignInProviderKey = @"Facebook";
NSString *const AWSFacebookSignInProviderUserNameKey = @"Facebook.userName";
NSString *const AWSFacebookSignInProviderImageURLKey = @"Facebook.imageURL";

@interface AWSIdentityManager()

- (void)completeLogin:(NSDictionary *)logins;

@end

@interface AWSFacebookSignInProvider()

@property (strong, nonatomic) FBSDKLoginManager *facebookLogin;

@property (strong, nonatomic) NSString *userName;
@property (strong, nonatomic) NSURL *imageURL;

@end

@implementation AWSFacebookSignInProvider

+ (instancetype)sharedInstance {
    static AWSFacebookSignInProvider *_sharedInstance = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _sharedInstance = [AWSFacebookSignInProvider new];
    });

    return _sharedInstance;
}

- (BOOL)isLoggedIn {
    BOOL loggedIn = [FBSDKAccessToken currentAccessToken] != nil;
    return [[NSUserDefaults standardUserDefaults] objectForKey:AWSFacebookSignInProviderKey] != nil && loggedIn;
}

- (NSString *)userName {
    return [[NSUserDefaults standardUserDefaults] objectForKey:AWSFacebookSignInProviderUserNameKey];
}

- (void)setUserName:(NSString *)userName {
    [[NSUserDefaults standardUserDefaults] setObject:userName
                                              forKey:AWSFacebookSignInProviderUserNameKey];
}

- (NSURL *)imageURL {
    return [NSURL URLWithString:[[NSUserDefaults standardUserDefaults] objectForKey:AWSFacebookSignInProviderImageURLKey]];
}

- (void)setImageURL:(NSURL *)imageURL {
    [[NSUserDefaults standardUserDefaults] setObject:imageURL.absoluteString
                                              forKey:AWSFacebookSignInProviderImageURLKey];
}

- (void)reloadSession {
    if ([[NSUserDefaults standardUserDefaults] objectForKey:AWSFacebookSignInProviderKey]
        && [FBSDKAccessToken currentAccessToken]) {
        [self completeLogin];
    }
}

- (void)completeLogin {
    [[NSUserDefaults standardUserDefaults] setObject:@"YES"
                                              forKey:AWSFacebookSignInProviderKey];
    [[AWSIdentityManager sharedInstance] completeLogin:@{@"graph.facebook.com": [FBSDKAccessToken currentAccessToken].tokenString}];

    FBSDKGraphRequest *requestForImageUrl = [[FBSDKGraphRequest alloc] initWithGraphPath:@"me"
                                                                              parameters:@{@"fields" : @"picture.type(large)"}];
    [requestForImageUrl startWithCompletionHandler:^(FBSDKGraphRequestConnection *connection,
                                                     NSDictionary *result,
                                                     NSError *queryError) {
        self.imageURL = [NSURL URLWithString:result[@"picture"][@"data"][@"url"]];
    }];

    FBSDKGraphRequest *requestForName = [[FBSDKGraphRequest alloc] initWithGraphPath:@"me"
                                                                          parameters:nil];
    [requestForName startWithCompletionHandler:^(FBSDKGraphRequestConnection *connection,
                                                 NSDictionary *result,
                                                 NSError *queryError) {
        self.userName = result[@"name"];
    }];
}

- (void)login {
    if ([FBSDKAccessToken currentAccessToken]) {
        [self completeLogin];
        return;
    }

    if (!self.facebookLogin)
        self.facebookLogin = [FBSDKLoginManager new];

    [self.facebookLogin logInWithReadPermissions:nil
                                         handler:^(FBSDKLoginManagerLoginResult *result, NSError *error) {
                                             if (error) {
                                                 //[[AWSIdentityManager errorAlert:[NSString stringWithFormat:@"Error logging in with FB: %@", error.localizedDescription]] show];
                                             } else if (result.isCancelled) {
                                                 // Login canceled, do nothing
                                             } else {
                                                 [self completeLogin];
                                             }
                                         }];
}

- (void)logout {
    [[NSUserDefaults standardUserDefaults] removeObjectForKey:AWSFacebookSignInProviderKey];
    if (!self.facebookLogin) {
        self.facebookLogin = [FBSDKLoginManager new];
    }

    [self.facebookLogin logOut];
}

- (BOOL)application:(UIApplication *)application
didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    return [[FBSDKApplicationDelegate sharedInstance] application:application
                                    didFinishLaunchingWithOptions:launchOptions];
}

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation {
    if ([[FBSDKApplicationDelegate sharedInstance] application:application
                                                       openURL:url
                                             sourceApplication:sourceApplication
                                                    annotation:annotation]) {
        return YES;
    }
    
    return NO;
}

@end
